version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"

  backend:
    build:
      context: .
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/mydb?schema=public"
      REDIS_URL: "redis://redis:6379"  # Use the Redis service name here
      JWT_SECRET: "JWTS3CR3T"
    depends_on:
      - postgres
      - redis
    ports:
      - "4000:4000"
      - "5555:5555"
    command: /bin/sh -c "npx prisma migrate deploy && npx prisma generate && npm run start:dev"
volumes:
  postgres_data:
